"""empty message

Revision ID: e7421431e648
Revises: 4272e04eab36
Create Date: 2026-04-20 22:56:51.553710

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'e7421431e648'
down_revision = '4272e04eab36'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('habito_registro',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('habito_id', sa.Integer(), nullable=False),
    sa.Column('fecha', sa.Date(), nullable=False),
    sa.Column('completado', sa.Boolean(), nullable=False),
    sa.ForeignKeyConstraint(['habito_id'], ['habito.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('habito_registro')
    # ### end Alembic commands ###
